version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\KScratch.Contract" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\KScratch.Entity" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\KScratch.Portable" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\KScratchLog" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\KScratch.Contract" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\KScratch.Entity" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\KScratch.Portable" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet publish "src\KScratchLog" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\ConsoleApplication
test_script:
- dotnet test "src\KScratch.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
