
version: '1.0.{build}'
configuration:
- Release
platform:
- win7-x64
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
#install:
#- ps: appveyor DownloadFile https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe -FileName "c:\dotnet.exe"
#- cmd: call c:\dotnet.exe /quiet
before_build:
- appveyor-retry dotnet restore src\ks.model -v Minimal -r %PLATFORM%
- appveyor-retry dotnet restore src\ks -v Minimal -r %PLATFORM%
build_script:
- dotnet build "src\ks.model" -c %CONFIGURATION% -r %PLATFORM%  --no-dependencies --version-suffix %LABEL%
- dotnet build "src\ks" -c %CONFIGURATION% -r %PLATFORM% --version-suffix %LABEL%
after_build:
- dotnet publish "src\ks" -c %CONFIGURATION% -r %PLATFORM% --no-build --version-suffix %LABEL% -o artifacts\%PLATFORM%
- 7z a zip\ks_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*.*
#test_script:
#- dotnet test "src\KScratch.Tests" -c %CONFIGURATION%
artifacts:
#- path: zip\**\*.*
- path: zip\ks_$(platform).zip
  name: arti_$(platform)
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
